# Generated by Django 6.0.7 on 2026-07-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projectstack_projecttechstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstack',
            name='project_views',
            field=models.IntegerField(default=0),
        ),
    ]
