# Generated by Django 6.0.7 on 2026-07-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_usertechstack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertechstack',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_tech_stack',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectstack',
            name='project_tech_stack',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='ProjectTechStack',
        ),
        migrations.DeleteModel(
            name='UserTechStack',
        ),
    ]
