# Generated by Django 6.0.7 on 2026-07-19 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_usertechstack_user_customuser_user_tech_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
