# Generated by Django 6.0.7 on 2026-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tech_field',
            field=models.CharField(default='', max_length=500),
        ),
    ]
