# Generated by Django 6.0.7 on 2026-07-19 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customuser_tech_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225)),
                ('job_title', models.CharField(max_length=225)),
                ('employment_type', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField(null=True)),
                ('short_description', models.TextField()),
                ('key_responsibilities', models.TextField(max_length=1000)),
                ('company_website', models.URLField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], max_length=225, null=True)),
                ('working_currently', models.BooleanField(default=False)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
