# Generated by Django 6.0.7 on 2026-07-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexperience',
            name='tech_stack',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='key_responsibilities',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
