# Generated by Django 6.0.7 on 2026-07-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userexperience_tech_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='professional_headlines',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='professional_summary',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
