# Generated by Django 6.0.7 on 2026-07-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_clientcontactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_of_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
