# Generated by Django 6.0.7 on 2026-07-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_customuser_number_of_clicks_portfolioview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
